//! MLP forward pass — INT8 quantized port of `policy.onnx`.
//!
//! Reference C++ source:
//! - `modules/atom01_train/robolab/robolab/tasks/direct/base/base_env.py:146-187`
//! - `modules/atom01_train/robolab/scripts/rsl_rl/play.py:353-365` (export to ONNX)
//!
//! Architecture: 780 → 512 → 256 → 128 → 23 with ELU activation.
//! Quantization: per-tensor symmetric INT8, FP32 activations.
//!
//! Generated by `tools/quantize_onnx.py` from a trained policy.onnx (Phase 1).

use crate::config::{ACTION_SCALE, CLIP_ACTIONS, DEFAULT_JOINT_ANGLES, USD2URDF};

pub const INPUT_DIM: usize = 780;
pub const OUTPUT_DIM: usize = 23;
pub const LAYER_DIMS: [usize; 5] = [780, 512, 256, 128, 23];

/// INT8 weights, row-major [out_dim × in_dim], generated by `tools/quantize_onnx.py`.
///
/// File sizes (host path): `weights/w{i}_int8.bin` = `in_dim * out_dim` bytes.
pub mod weights {
    pub const W1_BYTES: &[u8] = include_bytes!("../weights/w1_int8.bin");
    pub const W2_BYTES: &[u8] = include_bytes!("../weights/w2_int8.bin");
    pub const W3_BYTES: &[u8] = include_bytes!("../weights/w3_int8.bin");
    pub const W4_BYTES: &[u8] = include_bytes!("../weights/w4_int8.bin");
    pub const B1_BYTES: &[u8] = include_bytes!("../weights/b1_int8.bin");
    pub const B2_BYTES: &[u8] = include_bytes!("../weights/b2_int8.bin");
    pub const B3_BYTES: &[u8] = include_bytes!("../weights/b3_int8.bin");
    pub const B4_BYTES: &[u8] = include_bytes!("../weights/b4_int8.bin");
}

/// Per-layer dequantization scales (FP32 per-tensor scale, from manifest.json).
/// Layout: scale[i] = (w_scale, b_scale) for layer i (0-indexed).
pub const SCALES: [(f32, f32); 4] = [
    (0.001_411_7, 1.0),
    (0.001_570_0, 1.0),
    (0.001_847_1, 1.0),
    (0.002_688_7, 1.0),
];

/// ELU activation with Taylor-series approximation of `e^x - 1` for negative `x`.
///
/// Accurate to ~1e-5 for `|x| < 3`. Avoids `libm` dependency in `no_std`.
/// NaN collapses to 0; Inf passes through (ELU(+Inf) = +Inf mathematically).
#[inline]
pub fn elu(x: f32) -> f32 {
    if x.is_nan() { return 0.0; }
    if x >= 0.0 {
        x
    } else {
        let x2 = x * x;
        let x3 = x2 * x;
        let x4 = x2 * x2;
        x + x2 * 0.5 + x3 * (1.0 / 6.0) + x4 * (1.0 / 24.0) + (x4 * x) * (1.0 / 120.0)
    }
}

#[inline]
pub fn clip(x: f32, lo: f32, hi: f32) -> f32 {
    if x.is_nan() { 0.0 } else if x < lo { lo } else if x > hi { hi } else { x }
}

/// Stateless MLP forward + action post-processing.
pub struct Mlp;

impl Mlp {
    pub const fn new() -> Self {
        Self
    }

    /// INT8 forward pass through 4 linear + ELU layers.
    ///
    /// Input: `stacked_obs` contains 10 frames × 78 floats = 780 total.
    /// Output: `raw_action` filled with pre-clip, pre-scale, pre-offset values
    /// (i.e., output of the final linear layer).
    pub fn forward_int8(stacked_obs: &[f32; INPUT_DIM], raw_action: &mut [f32; OUTPUT_DIM]) {
        let weight_bytes: [&[u8]; 4] = [
            weights::W1_BYTES, weights::W2_BYTES, weights::W3_BYTES, weights::W4_BYTES,
        ];
        let bias_bytes: [&[u8]; 4] = [
            weights::B1_BYTES, weights::B2_BYTES, weights::B3_BYTES, weights::B4_BYTES,
        ];

        let mut h1 = [0.0f32; 512];
        let mut h2 = [0.0f32; 256];
        let mut h3 = [0.0f32; 128];
        let mut h_out = [0.0f32; 23];

        Self::int8_gemm(&mut h1, stacked_obs, weight_bytes[0], bias_bytes[0], SCALES[0], (512, 780));
        Self::apply_elu(&mut h1);
        Self::int8_gemm(&mut h2, &h1, weight_bytes[1], bias_bytes[1], SCALES[1], (256, 512));
        Self::apply_elu(&mut h2);
        Self::int8_gemm(&mut h3, &h2, weight_bytes[2], bias_bytes[2], SCALES[2], (128, 256));
        Self::apply_elu(&mut h3);
        Self::int8_gemm(&mut h_out, &h3, weight_bytes[3], bias_bytes[3], SCALES[3], (23, 128));

        raw_action.copy_from_slice(&h_out);
    }

/// INT8 quantized matrix-vector multiply: `out = scale_w * (W_q @ x) + scale_b * b_q`.
///
/// Weights stored row-major [out_dim × in_dim].
/// `x` is f32 input vector of length `in_dim`.
/// `out` is f32 output vector of length `out_dim`.
/// `w_q` is `out_dim * in_dim` bytes (i8), `b_q` is `out_dim` bytes (i8).
///
/// Accumulator uses saturating_add so that pathologically large inputs (e.g.
/// IMU spikes) cannot wrap i32 silently and produce garbage output.
    fn int8_gemm(out: &mut [f32], x: &[f32], w_q: &[u8], b_q: &[u8], scales: (f32, f32), dims: (usize, usize)) {
        let (out_dim, in_dim) = dims;
        let (w_scale, b_scale) = scales;
        for i in 0..out_dim {
            let row_offset = i * in_dim;
            let mut acc: i32 = 0;
            for j in 0..in_dim {
                let w_qi = w_q[row_offset + j] as i8 as i32;
                let xj = x[j] as i32;
                acc = acc.saturating_add(w_qi.saturating_mul(xj));
            }
            let b_qi = b_q[i] as i8 as i32;
            out[i] = (acc as f32) * w_scale + (b_qi as f32) * b_scale;
        }
    }

    fn apply_elu(buf: &mut [f32]) {
        for v in buf.iter_mut() {
            *v = elu(*v);
        }
    }

    /// Apply post-processing: clip → scale → USD→URDF → add default angle.
    pub fn post_process(raw_action: &[f32; OUTPUT_DIM], out_action: &mut [f32; OUTPUT_DIM]) {
        for i in 0..OUTPUT_DIM {
            let clipped = clip(raw_action[i], -CLIP_ACTIONS, CLIP_ACTIONS);
            out_action[USD2URDF[i]] = clipped * ACTION_SCALE + DEFAULT_JOINT_ANGLES[USD2URDF[i]];
        }
    }
}

impl Default for Mlp {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn elu_positive_is_identity() {
        assert_eq!(elu(0.0), 0.0);
        assert_eq!(elu(1.0), 1.0);
        assert_eq!(elu(100.0), 100.0);
    }

    #[test]
    fn elu_negative_is_below_zero() {
        for &x in &[-0.1_f32, -0.5, -1.0, -2.0, -3.0, -10.0] {
            let y = elu(x);
            assert!(y < 0.0, "elu({x}) = {y}, expected negative");
            assert!(y > x, "elu({x}) = {y}, expected > x (input)");
        }
    }

    #[test]
    fn clip_clamps_below_and_above() {
        assert_eq!(clip(-200.0, -100.0, 100.0), -100.0);
        assert_eq!(clip(200.0, -100.0, 100.0), 100.0);
        assert_eq!(clip(0.0, -100.0, 100.0), 0.0);
    }

    #[test]
    fn elu_nan_collapses_to_zero() {
        // NaN must NOT propagate through the MLP activation; collapse to
        // 0 so the layer can continue computing meaningful downstream values.
        assert_eq!(elu(f32::NAN), 0.0);
        assert_eq!(elu(f32::INFINITY), f32::INFINITY);
        assert_eq!(elu(f32::NEG_INFINITY), f32::NEG_INFINITY);
    }

    #[test]
    fn clip_nan_falls_back_to_safe_neutral() {
        // NaN must NOT propagate through clip — robot control must not see NaN.
        assert_eq!(clip(f32::NAN, -1.0, 1.0), 0.0);
        assert_eq!(clip(f32::INFINITY, -1.0, 1.0), 1.0);
        assert_eq!(clip(f32::NEG_INFINITY, -1.0, 1.0), -1.0);
    }

    #[test]
    fn post_process_zero_input_yields_default_angles() {
        let raw = [0.0; OUTPUT_DIM];
        let mut out = [0.0_f32; OUTPUT_DIM];
        Mlp::post_process(&raw, &mut out);
        for i in 0..OUTPUT_DIM {
            assert!(
                (out[i] - DEFAULT_JOINT_ANGLES[i]).abs() < 1e-5,
                "joint {}: expected {}, got {}", i, DEFAULT_JOINT_ANGLES[i], out[i]
            );
        }
    }

    #[test]
    fn forward_int8_runs_without_panic() {
        let obs = [0.0f32; INPUT_DIM];
        let mut out = [0.0f32; OUTPUT_DIM];
        Mlp::forward_int8(&obs, &mut out);
        let mut out2 = [0.0f32; OUTPUT_DIM];
        Mlp::forward_int8(&obs, &mut out2);
        assert_eq!(out, out2, "INT8 forward must be deterministic");
    }

    #[test]
    fn forward_int8_dimensions_match_spec() {
        assert_eq!(weights::W1_BYTES.len(), 780 * 512);
        assert_eq!(weights::W2_BYTES.len(), 512 * 256);
        assert_eq!(weights::W3_BYTES.len(), 256 * 128);
        assert_eq!(weights::W4_BYTES.len(), 128 * 23);
        assert_eq!(weights::B1_BYTES.len(), 512);
        assert_eq!(weights::B2_BYTES.len(), 256);
        assert_eq!(weights::B3_BYTES.len(), 128);
        assert_eq!(weights::B4_BYTES.len(), 23);
    }

    #[test]
    fn weight_scales_match_manifest() {
        for &(w_s, b_s) in &SCALES {
            assert!(w_s > 0.0 && w_s < 1.0, "w_scale out of range: {w_s}");
            assert!(b_s > 0.0 && b_s < 1.0, "b_scale out of range: {b_s}");
        }
    }
}
